### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/SBM-BoneTorch#10]
Whenever a player joins a server the mod will be listed like this rather than the mod followed by its version 
bonetorch@@MAJOR@.@MINOR@.@REVIS@.@BUILD@

**Comment by Tommeh1** [comment]
Same applies to wooden shears

**Comment by DarkGuardsman** [comment]
@dmodoomsirius Is this a you bug or a me fail?

**Comment by dmodoomsirius** [comment]
@CraftalotReloaded what does the jar file say. like "SBM-BoneTorch-1.12.0.14.8.jar" or something like that? so i know what branch to look at.

**Comment by DarkGuardsman** [comment]
I assume 1.12

**Comment by Tommeh1** [comment]
Yes, it is 1.12
Btw i'm Tommeh @dmodoomsirius

**Comment by bl4ckscor3** [comment]
Closing due to no longer supporting 1.12.2.
