### ISSUE TITLE
1.9.4-0.0.1b2 crashes dedicated Forge 1.9.4 build 1954 on startup

### ISSUE THREAD

**Issue by kreezxil** [BuiltBrokenModding/SBM-BoneTorch#2]
Issue:  Bone Torch 1.9.4-0.0.1b2 crashes dedicated Forge 1.9.4 build 1954 on startup seems to be looking for client side classes

https://gist.github.com/1dbeda30fb4c256b657c2f66cbd11baf

https://gist.github.com/8990681da7fecc635e0e787411ec2214

**Comment by DarkGuardsman** [comment]
I'll have to look at it here later, we let a 3rd party developer do the port for us. Looks like he pushed client side only code to the server side code.

**Comment by kolatra** [comment]
Will fix momentarily.

**Comment by dmodoomsirius** [comment]
new build is on curse. Enjoy and thank you for the bug report!
