### ISSUE TITLE
Bone torches do not have a localized name

### ISSUE THREAD

**Issue by WolfieWaffle** [BuiltBrokenModding/SBM-BoneTorch#3]
In the most recent version, bone torches have the name "tile.null.name".

**Comment by dmodoomsirius** [comment]
The most recent version being the 1.9.4 version right?

**Comment by DarkGuardsman** [comment]
I'll look into this later today and see what is the cause

**Comment by dmodoomsirius** [comment]
is this placed in world or inventory?

**Comment by kolatra** [comment]
I just forgot to set the unlocalized name for the Bone Torch in the Block class, it's not done automatically anymore for some reason. 

Fixed now. :)
